### PR TITLE
Fix compile issue and potential race condition

### PR DESCRIPTION
**Pull request by noiz**
- Fixed the race condition I mentioned
- Also fixed the compile error trying to assign `false` to a `int32`

### CODE REVIEW

**Comment by alaingilbert** [comment]
Not sure why you removed the defer ?

**Comment by noiz** [comment]
> Not sure why you removed the defer ?

At least on the raspberry pi that I am running on I would see that calling `_ = b.updatePresence()` would have the `executeCallback()` get called for the presence update before the `defer atomic.StoreInt32(&b.presenceTaskStarted, 0)` would be able to run in the goroutine.  This would get me stuck in a state where presence updates would stop going out since another presence update task would not start.

**Comment by alaingilbert** [comment]
Not sure, bit it looks like the whole condition (atomic) isn't really useful at all ?

**Comment by alaingilbert** [comment]
If it really is useful, you'd definitely want to make sure it is reset to 0 where the return is as well

**Comment by noiz** [comment]
It is useful, we need something to protect us from starting two presence update tasks (i.e. if someone calls `SetStatus()` while an update presence task is already running we don't want to start another one).  The main thing we are protecting against is the long sleep that is happening in the goroutine.  Once the sleep is over we are now fine to start a new presence update task since we are calling `b.updatePresence()`.  I am just removing it from defer since we could have the websocket respond and process that response before the defer gets called to allow us to start another update presence task.

**Comment by dnathe4th** [comment]
But isn't setting `b.presenceTaskStarted` to zero before actually processing the presenceUpdate problematic?

**Comment by alaingilbert** [comment]
Reset the value where the return statement is and I'll merge the pr

**Comment by dnathe4th** [comment]
Putting up https://github.com/alaingilbert/ttapi/pull/8 as an alternative for how I would have done that presence check, if there's interest in seeing another approach.

**Comment by noiz** [comment]
If I reset it after the return statement then it will not work for me since I am seeing exactly what I am describing.  Not sure if you follow what I am saying still.  So made a diagram showing the two threads running and what I am seeing.  These are running from top to bottom with the calls that happen in the main `Start()` thread and the goroutine thread we are creating:

image

So in the diagram above is the race condition that I am hitting 100% if I don't update the atomic before calling updatePresence.

I don't think it is problematic to reset it it before calling `presenceUpdate` since this is basically making sure we are only ever starting this task to call it at least once per interval period.  If one or more `presenceUpdate` calls happens it is fine, we just only want to be responding to at most one at a time (i.e. not having multiple presence tasks running concurrently).

**Comment by noiz** [comment]
Alright, so went back to the source and hopefully have a solution that both of you will be happy with.  What I saw inspecting web traffic from chrome is that the web client actually only sets its presence every 10 seconds (or every interval).  So even if you change your status to unavailable it waits until the next interval elapses to update your presence to that new status.  So right now this library was allowing users to set their status and a message would go out any time a new status was set.  So I changed my branch now to match what the web client is doing.  If a user tries to set a new status it waits until the next interval elapses and then will set that new status just like the web client.  Gonna let this soak test for a couple days without restarting my bot to make sure it still looks good.

I think in a lot of ways it makes this code cleaner and easier to be thread safe since we will always be kicking off the presence update once on startup then rely on this new goroutine to kick off the next presence update after the interval expires.

**Comment by dnathe4th** [comment]
This looks good, I closed both of my PRs. This will trigger itself due to the first `"~m~10~m~no_session"` message received. I still think it is a bit cleaner in its own loop rather than implicitly re-triggering based on its own response, but I do like that you get rid of the atomics work.

I support this merge @alaingilbert , and if nothing else it will get master back to a working state!

**Comment by noiz** [comment]
So I am kind of hitting my head against a wall debugging this issue.  With the change in this PR I saw in the logs that we send a presence update out and never get a response back.  So I went back to just having a goroutine that loops every 10 seconds and sends a presence update.  I see the same thing with that code, I send out a presence update, don't get a response back, but then we never send out more presence updates.  The code I am testing looks like this:
```
	if bytes.Equal(msg, []byte("~m~10~m~no_session")) {
		b.emit(ready, nil)
		SGo(func() {
			_ = b.updatePresence()
			_ = b.userModify(H{"laptop": b.laptop})
			if b.roomID != "" {
				if err := b.roomRegister(b.roomID); err != nil {
					logrus.Error(err)
					b.roomID = ""
				}
			}
		})
		SGo(func() {
			for {
				select {
				case <-time.After(10 * time.Second):
				case <-b.ctx.Done():
					return
				}
				_ = b.updatePresence()
			}
		})
		return
	}
```
I was hoping to see the catch for a panic for `SGo` but I do not see any error returned.  I also put a print in the return case but did not see that print either.  So not really sure why after running for around a day or two the presence updates just stop going out.  I see that other Rx/Tx events are going out (my bot is upvoting, responding to other commands, etc.) but some reason this goroutine for sending presence updates dies.  I am still somewhat new with Golang so any clues on how I could debug this further?  Or should I just live with having to restart my bot when this issue happens?

**Comment by alaingilbert** [comment]
I did something really bad, which is, I force pushed master to the commit it was before we made any changes for this issue.
(sorry if it bothers anyone)

That being said, I'll try to run a bot for a few days and see if I get any issue.

**Comment by noiz** [comment]
So thinking about this more it actually is pretty simple what is happening.  In the case where we get stuck we are doing a Tx to update presence and never get an Rx back acknowledging the presence update happened.  So we end up getting stuck in the select statement here at the end of the function:
```
func (b *Bot) tx(payload H, res interface{}) {
	ctx, cancel := context.WithCancel(context.Background())
	clb := func(rawJson []byte) {
		switch v := res.(type) {
		case *[]byte:
			*v = rawJson
		default:
			if err := json.Unmarshal(rawJson, &res); err != nil {
				logrus.Error(err)
			}
		}
		cancel()
	}
	b.txCh <- TxMsg{Payload: payload, Callback: clb}
	select {
	case <-ctx.Done():
	case <-b.ctx.Done():
	}
}
```
So our presence update gets stuck in the `b.unackMsgs` and we never execute the callback so we just sit there waiting for the presence update to finish and can never send another presence update.  Not sure how you want to solve this but this does seem to be the root cause.  We need a way to timeout a Tx message going out that doesn't ever get a response.

**Comment by dnathe4th** [comment]
This is a good example of why I liked the intentional loop instead of
triggering a new presence update as a delay after a previous Rx. Is there a
reason we care about the response at all? Maybe just for the interval
change? Other than that these could be fire-and-forget I think right?

**Comment by noiz** [comment]
This is affecting the loop version.  The loop is still calling presence update and then can never return since it is waiting for the callback to fire.  The code that I have running now that still gets stuck:
```
		SGo(func() {
			for {
				select {
				case <-time.After(10 * time.Second):
				case <-b.ctx.Done():
					return
				}
				_ = b.updatePresence() <- Stuck here since we are stuck in my code snippet in my previous comment
			}
		})
```

**Comment by alaingilbert** [comment]
This commit should fix the issue that you have https://github.com/alaingilbert/ttapi/commit/f5742d175f04946b899389b8dd37e0fc444b6bc4

So if it takes more than 5 seconds to receive a message from TT socket, it will timeout.

I guess that if it happens a lot, `unackMsgs` could grow and use memory for no reason.
We could have a timestamp in it and periodically cleanup "old" unacked messages.

**Comment by noiz** [comment]
Alright, just updated to the latest code and will test this for a couple days to see that I do not go offline.  I agree with the `unackMsgs` growing but hopefully won't be too bad.  Right now running the bot on my raspberry pi 3b it is barely using 2% of memory and I feel like I restart the bot at least once a week.  As long as I can stay online it should be fine for now.

**Comment by alaingilbert** [comment]
@noiz no more issues ?

**Comment by noiz** [comment]
> @noiz no more issues ?

Yeah, ran for 2 days without seeing my bot go offline.  Saw this morning that systemd restarted my bot since I got this error: `level=error msg="socket eof:EOF"` but I don't think that is related to your changes (I have seen that before when running the bot for long periods of time).  Will close this PR for now and open a new issue if I encounter the bot going offline again, but it looks fixed.

**Pull request closed without merging**
